# The Python  Tutorial

This document shows a high-level tutorial about Python. The tutorial presented in this document was taken from python.org. So, the examples and its respective explanation is the same in most of the cases.

## 1. Whetting you Appetite

Python is simple to use, but it is a real programming language, offering much more structure and support for large programs than shell scripts or batch files can offer. On the other hand, Python also offers much more error checking than C, and, being a very-high-level language, it has high-level data types built in, such as flexible arrays and dictionaries. Because of its more general data types Python is applicable to a much larger problem domain than Awk or even Perl, yet many things are at least as easy in Python as in those languages.

Python allows you to split your program into modules that can be reused in other Python programs. It comes with a large collection of standard modules that you can use as the basis of your programs — or as examples to start learning to program in Python. Some of these modules provide things like file I/O, system calls, sockets, and even interfaces to graphical user interface toolkits like Tk.

Python is an interpreted language, which can save you considerable time during program development because no compilation and linking is necessary. The interpreter can be used interactively, which makes it easy to experiment with features of the language, to write throw-away programs, or to test functions during bottom-up program development. It is also a handy desk calculator.

Python enables programs to be written compactly and readably. Programs written in Python are typically much shorter than equivalent C, C++, or Java programs, for several reasons:

- the high-level data types allow you to express complex operations in a single statement;

- statement grouping is done by indentation instead of beginning and ending brackets;

- no variable or argument declarations are necessary.

Python is extensible: if you know how to program in C it is easy to add a new built-in function or module to the interpreter, either to perform critical operations at maximum speed, or to link Python programs to libraries that may only be available in binary form (such as a vendor-specific graphics library). Once you are really hooked, you can link the Python interpreter into an application written in C and use it as an extension or command language for that application.

## 2. Using the Python Interpreter

### 2.1 Invoking the Interpreter

The Python interpreter is usually installed as /usr/local/bin/python3.8 on those machines where it is available; putting /usr/local/bin in your Unix shell’s search path makes it possible to start it by typing the command:

Typing an end-of-file character (Control-D on Unix, Control-Z on Windows) at the primary prompt causes the interpreter to exit with a zero exit status. If that doesn’t work, you can exit the interpreter by typing the following command: quit().

A second way of starting the interpreter is python -c command [arg] ..., which executes the statement(s) in command, analogous to the shell’s -c option. Since Python statements often contain spaces or other characters that are special to the shell, it is usually advised to quote command in its entirety with single quotes.

Some Python modules are also useful as scripts. These can be invoked using python -m module [arg] ..., which executes the source file for module as if you had spelled out its full name on the command line.

When a script file is used, it is sometimes useful to be able to run the script and enter interactive mode afterwards. This can be done by passing -i before the script.

#### 2.1.1 Argument Passing

When known to the interpreter, the script name and additional arguments thereafter are turned into a list of strings and assigned to the argv variable in the sys module. You can access this list by executing import sys. The length of the list is at least one; when no script and no arguments are given, sys.argv[0] is an empty string. When the script name is given as '-' (meaning standard input), sys.argv[0] is set to '-'. When -c command is used, sys.argv[0] is set to '-c'. When -m module is used, sys.argv[0] is set to the full name of the located module. Options found after -c command or -m module are not consumed by the Python interpreter’s option processing but left in sys.argv for the command or module to handle.

#### 2.1.2 Interactive Mode

When commands are read from a tty, the interpreter is said to be in interactive mode. In this mode it prompts for the next command with the primary prompt, usually three greater-than signs (>>>); for continuation lines it prompts with the secondary prompt, by default three dots (...). The interpreter prints a welcome message stating its version number and a copyright notice before printing the first prompt:

### 2.2 The Interpreter and Its Environment

#### 2.2.1 Source Code Encoding

By default, Python source files are treated as encoded in UTF-8. In that encoding, characters of most languages in the world can be used simultaneously in string literals, identifiers and comments — although the standard library only uses ASCII characters for identifiers, a convention that any portable code should follow. To display all these characters properly, your editor must recognize that the file is UTF-8, and it must use a font that supports all the characters in the file.

To declare an encoding other than the default one, a special comment line should be added as the first line of the file. The syntax is as follows:

where encoding is one of the valid codecs supported by Python.

For example, to declare that Windows-1252 encoding is to be used, the first line of your source code file should be:

One exception to the first line rule is when the source code starts with a UNIX “shebang” line. In this case, the encoding declaration should be added as the second line of the file. For example:

## 3. An Informal Introduction to Python

### 3.1 Using Python as a Calculator

#### 3.1.1 Numbers

The interpreter acts as a simple calculator: ypu can type an expression at it and it will write the value. Expression syntax is straifhtforward: the operators +, -, * and / work just like in most other languages; parentheses can be used for grouping. For example:

In [1]:
2+2

4

In [2]:
50 - 5*6

20

In [3]:
(50 - 5*6) / 4

5.0

In [4]:
8 / 5 # division always return a floating point number

1.6

* Note: The integer numbers (e.g. 2,4, 20) have type int, the ones with a fractional part (e.g. 5.0, 1.6) have type float.

Division (/) always returns a float. To do floor division and get an integer result (discarding any fractional result) you can use the // operator; to calculate the remainder you can use %:

In [5]:
17 / 3 # classic division returns a float

5.666666666666667

In [6]:
17 // 3 # floor division discards the fractional part

5

In [7]:
17 % 3 # the % operator returns the remainder of the division

2

In [8]:
5 * 3 + 2 # result * divisor + remainder

17

With Python, it is possible to use the ** operator to calculate powers:

In [9]:
5 ** 2 # 5 squared

25

In [10]:
2 ** 7 # 2 to the power of 7

128

The equal sign (=) is used to assign a value to a variable. Afterwards, no result is displayed before the next interactive prompt:

In [11]:
width = 20
height = 5 * 9
width * height

900

If a variable is not “defined” (assigned a value), trying to use it will give you an error:

In [12]:
n # try to access an undefined variable

NameError: name 'n' is not defined

There is full support for floating point; operators with mixed type operands convert the integer operand to floating point:

In [13]:
4 * 3.75 - 1

14.0

In interactive mode, the last printed expression is assigned to the variable _. This means that when you are using Python as a desk calculator, it is somewhat easier to continue calculations, for example:

In [14]:
tax = 12.5 / 100
price = 100.50
price * tax

12.5625

In [15]:
price + _

113.0625

In [16]:
round(_, 2)

113.06

This variable should be treated as read-only by the user. Don’t explicitly assign a value to it — you would create an independent local variable with the same name masking the built-in variable with its magic behavior.

In addition to int and float, Python supports other types of numbers, such as Decimal and Fraction. Python also has built-in support for complex numbers, and uses the j or J suffix to indicate the imaginary part (e.g. 3+5j).


#### 3.1.2 Strings

Python can also manipulate strings, which can be expressed in several ways. They can be enclosed in a single quotes ('..') or double quotes ("...") with the same result. To escape quotes a \ can be used.

In [17]:
'spam eggs' # single quotes

'spam eggs'

In [18]:
'doesn\'t' # use \' to escape the single quote...

"doesn't"

In [19]:
"doesn't" # ...or use double quotes instead

"doesn't"

In [20]:
'"Yes," they said.'

'"Yes," they said.'

In [21]:
"\"Yes,\" they said."

'"Yes," they said.'

In [22]:
'"Isn\'t," they said.'

'"Isn\'t," they said.'

In the interactive interpreter, the output string is enclosed in quotes and special characters are escaped with backslashes. While this might sometimes look different from the input (the enclosing quotes could change), the two strings are equivalent. The string is enclosed in double quotes if the string contains a single quote and no double quotes, otherwise it is enclosed in single quotes. The print() function produces a more readable output, by omitting the enclosing quotes and by printing escaped and special characters:

In [23]:
'"Isn\'t," they said.'

'"Isn\'t," they said.'

In [24]:
print('"Isn\'t," they said.')

"Isn't," they said.


In [25]:
s = 'First line.\nSecond line.' # \n means newline

In [26]:
s # without print(), \n is included in the output

'First line.\nSecond line.'

In [27]:
print(s) # with print(), \n produces a new line

First line.
Second line.


If you don’t want characters prefaced by \ to be interpreted as special characters, you can use raw strings by adding an r before the first quote:

In [28]:
print('C:\some\name') # here \n means newline!

C:\some
ame


In [29]:
print(r'C:\some\name') # note the r before the quote

C:\some\name


String literals can span multiple lines. One way is using triple-quotes: """...""" or '''...'''. End of lines are automatically included in the string, but it’s possible to prevent this by adding a \ at the end of the line. For example:

In [30]:
print("""\
Usage: thingy [OPTIONS]
    -h                       Display this usage message
    -H hostname              Hostname to connect to
""")

Usage: thingy [OPTIONS]
    -h                       Display this usage message
    -H hostname              Hostname to connect to



Note that the initial newline is not included.

Strings can be concatenated (glued together) with the + operator, and repeated with *:

In [31]:
# 3 times 'un', followed by 'ium'
3 * 'un' + 'ium'

'unununium'

Two or more strings literals (i.e. the ones enclosed between quotes) next to each other are automatically concatenated.

In [32]:
'Py' 'thon'

'Python'

This feature is particulary useful when you want to break long strings:

In [33]:
text = ('Put several strings within parentheses '
       'to have them joined together')
text

'Put several strings within parentheses to have them joined together'

This only works with two literals though, not with variables or expressions:

In [34]:
prefix = 'Py'

In [35]:
prefix 'thon' # can't concatenate a variable and a string literal

SyntaxError: invalid syntax (<ipython-input-35-611f66a71513>, line 1)

In [36]:
('un' * 3) 'ium'

SyntaxError: invalid syntax (<ipython-input-36-f4764cbe42a8>, line 1)

If you want to concatenate variables or a variable and a literal, use +:

In [37]:
prefix + 'thon'

'Python'

Strings can be indexed (subscripted), with the first character having index 0. There is no separate character type; a character is simply a string of size one:

In [38]:
word = 'Python'

In [39]:
word[0] # character in position 0

'P'

In [40]:
word[5] # character in position 5

'n'

Indices may also be negative numbers, to start counting from the right:

In [41]:
word[-1] # last character

'n'

In [42]:
word[-2] # second-last character

'o'

In [43]:
word[-6]

'P'

Note that since -0 is the same as 0, negative indices start from -1.

In addition to indexing, slicing is also supported. While indexing is used to obtain individual characters, slicing allows you to obtain substring:

In [44]:
word[0:2] # characters from position 0 (included) to 2 (excluded)

'Py'

In [45]:
word[2:5]  # characters from position 2 (included) to 5 (excluded)

'tho'

Note how the start is always included, and the end always excluded. This makes sure that s[:i] + s[i:] is always equal to s:

In [46]:
word[:2] + word[2:]

'Python'

In [47]:
word[:4] + word[4:]

'Python'

Slice indices have useful defaults; an omitted first index defaults to zero, an omitted second index defaults to the size of the string being sliced.

In [48]:
word[:2]   # character from the beginning to position 2 (excluded)

'Py'

In [49]:
word[4:]   # characters from position 4 (included) to the end

'on'

In [50]:
word[-2:]  # characters from the second-last (included) to the end

'on'

One way to remember how slices work is to think of the indices as pointing between characters, with the left edge of the first character numbered 0. Then the right edge of the last character of a string of n characters has index n, for example:

The first row of numbers gives the position of the indices 0…6 in the string; the second row gives the corresponding negative indices. The slice from i to j consists of all characters between the edges labeled i and j, respectively.

For non-negative indices, the length of a slice is the difference of the indices, if both are within bounds. For example, the length of word[1:3] is 2.

Attempting to use an index that is too large will result in an error:

In [51]:
word[42] # the word only has 6 characters

IndexError: string index out of range

However, out of range slice indexes are handled gracefully when used for slicing:

In [52]:
word[4:42]

'on'

In [53]:
word[42:]

''

Python strings cannot be changed — they are immutable. Therefore, assigning to an indexed position in the string results in an error:

In [54]:
word[0] = 'J'

TypeError: 'str' object does not support item assignment

In [55]:
word[2:] = 'py'

TypeError: 'str' object does not support item assignment

If you need a different string, you should create a new one:

In [56]:
'J' + word[1:]

'Jython'

In [57]:
word[:2] + 'py'

'Pypy'

The built-in function len() returns the length of a string:

In [58]:
s = 'supercalifragilisticexpialidocious'

In [59]:
len(s)

34

#### 3.1.2 Lists

Python knows a number of compound data types, used to group together other values. The most versatile is the list, which can be written as a list of comma-separated values (items) between square brackets. Lists might contain items of different types, but usually the items all have the same type.

In [60]:
squares = [1, 4, 9, 16, 25]

In [61]:
squares

[1, 4, 9, 16, 25]

Like strings (and all other built-in sequence types), lists can be indexed and sliced:

In [62]:
squares[0]  # indexing returns the item

1

In [63]:
squares[-1]

25

In [64]:
squares[-3:]  # slicing returns a new list

[9, 16, 25]

All slice operations return a new list containing the requested elements. This means that the following slice returns a shallow copy of the list:

In [65]:
squares[:]

[1, 4, 9, 16, 25]

Lists also support operations like concatenation:

In [66]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Unlike strings, which are immutable, lists are a mutable type, i.e. it is possible to change their content:

In [67]:
cubes = [1, 8, 27, 65, 125]  # something's wrong here

In [68]:
4 ** 3  # the cube of 4 is 64, not 65!

64

In [69]:
cubes[3] = 64  # replace the wrong value

In [70]:
cubes

[1, 8, 27, 64, 125]

You can also add new items at the end of the list, by using the append() method:

In [71]:
cubes.append(216)  # add the cube of 6

In [72]:
cubes.append(7 ** 3)  # and the cube of 7

In [73]:
cubes

[1, 8, 27, 64, 125, 216, 343]

Assignment to slices is also possible, and this can even change the size of the list or clear it entirely:

In [74]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [75]:
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [76]:
# replace some values
letters[2:5] = ['C', 'D', 'E']

In [77]:
letters

['a', 'b', 'C', 'D', 'E', 'f', 'g']

In [78]:
# now remove them
letters[2:5] = []

In [79]:
letters

['a', 'b', 'f', 'g']

In [80]:
# clear the list by replacing all the elements with an empty list
letters[:] = []

In [81]:
letters

[]

The built-in function len() also applies to lists:

In [82]:
letters = ['a', 'b', 'c', 'd']

In [83]:
len(letters)

4

It is possible to nest lists (create lists containing other lists), for example

In [84]:
a = ['a', 'b', 'c']

In [85]:
n = [1, 2, 3]

In [86]:
x = [a, n]

In [87]:
x

[['a', 'b', 'c'], [1, 2, 3]]

In [88]:
x[0]

['a', 'b', 'c']

In [89]:
x[0][1]

'b'

### 3.2 First Steps Towards Programming

Of course, we can use Python for more complicated tasks than adding two and two together. For instance, we can write an initial sub-sequence of the Fibonacci series as follows:

In [90]:
# Fibonacci series:
# the sum of two elements defines the next
a, b = 0, 1

In [91]:
while a < 10:
    print(a)
    a, b = b, a+b

0
1
1
2
3
5
8


This example introduces several new features.

The first line contains a multiple assignment: the variables a and b simultaneously get the new values 0 and 1. On the last line this is used again, demonstrating that the expressions on the right-hand side are all evaluated first before any of the assignments take place. The right-hand side expressions are evaluated from the left to the right.

The while loop executes as long as the condition (here: a < 10) remains true. In Python any non-zero integer value is true; zero is false. The condition may also be a string or list value, in fact any sequence; anything with a non-zero length is true, empty sequences are false. The test used in the example is a simple comparison. The standard comparison operators are: < (less than), > (greater than), == (equal to), <= (less than or equal to), >= (greater than or equal to) and != (not equal to).

The body of the loop is indented: indentation is Python’s way of grouping statements. At the interactive prompt, you have to type a tab or space(s) for each indented line. In practice you will prepare more complicated input for Python with a text editor; all decent text editors have an auto-indent facility. When a compound statement is entered interactively, it must be followed by a blank line to indicate completion (since the parser cannot guess when you have typed the last line). Note that each line within a basic block must be indented by the same amount.

The print() function writes the value of the argument(s) it is given. It differs from just writing the expression you want to write in the way it handles multiple arguments, floating point quantities, and strings. Strings are printed without quotes, and a space is inserted between items, so you can format things nicely, like this:

In [92]:
i = 256*256

In [93]:
print('The value of i is', i)

The value of i is 65536


The keyword argument end can be used to avoid the newline after the output, or end the output with a different string:

In [94]:
a, b = 0, 1

In [95]:
while a < 1000:
    print(a, end=',')
    a, b = b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

## 4. More Control Flow Tools

Besides the while statement just introduced, Python uses the usual flow control statements known from other languages, with some twists.

### 4.1 if Statements

Perhaps the most well-known statement type is the if statement. For example:

In [96]:
x = int(input("Please enter an integer: "))

Please enter an integer: 42


In [97]:
if x < 0:
    x = 0
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')

More


There can be zero or more elif parts, and the else part is optional. The keyword ‘elif’ is short for ‘else if’, and is useful to avoid excessive indentation. An if … elif … elif … sequence is a substitute for the switch or case statements found in other languages.

### 4.2 for Statements

The for statement in Python differs a bit from what you may be used to in C or Pascal. Rather than always iterating over an arithmetic progression of numbers (like in Pascal), or giving the user the ability to define both the iteration step and halting condition (as C), Python’s for statement iterates over the items of any sequence (a list or a string), in the order that they appear in the sequence. For example:

In [98]:
# Measure some strings:
words = ['cat', 'window', 'defenestrate']

In [99]:
for w in words:
    print(w, len(w))

cat 3
window 6
defenestrate 12


Code that modifies a collection while iterating over that same collection can be tricky to get right. Instead, it is usually more straight-forward to loop over a copy of the collection or to create a new collection:

### 4.3 The range() Function

If you do need to iterate over a sequence of numbers, the built-in function range() comes in handy. It generates arithmetic progressions:

In [100]:
for i in range (5):
    print(i)

0
1
2
3
4


The given end point is never part of the generated sequence; range(10) generates 10 values, the legal indices for items of a sequence of length 10. It is possible to let the range start at another number, or to specify a different increment (even negative; sometimes this is called the ‘step’):

To iterate over the indices of a sequence, you can combine range() and len() as follows:

In [101]:
a = ['Mary', 'had', 'a', 'little', 'lamb']

In [102]:
for i in range(len(a)):
    print(i, a[i])

0 Mary
1 had
2 a
3 little
4 lamb


A strange thing happens if you print a range:

In [103]:
print(range(10))

range(0, 10)


In many ways the object returned by range() behaves as if it is a list, but in fact it isn’t. It is an object which returns the successive items of the desired sequence when you iterate over it, but it doesn’t really make the list, thus saving space.

We say such an object is iterable, that is, suitable as a target for functions and constructs that expect something from which they can obtain successive items until the supply is exhausted. We have seen that the for statement is such a construct, while an example of a function that takes an iterable is sum():

In [104]:
sum(range(4)) # 0 + 1 + 2 + 3

6

Below an example to get a list from a range:

In [105]:
list(range(4))

[0, 1, 2, 3]

### 4.4 break and continue Statements, and else Clauses on Loops

The break statement breaks out of the innermost enclosing for or while loop.

Loop statements may have an else clause; it is executed when the loop terminates through exhaustion of the iterable (with for) or when the condition becomes false (with while), but not when the loop is terminated by a break statement. This is exemplified by the following loop, which searches for prime numbers:

In [106]:
for n in range(2, 10):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n//x)
            break
    else:
        # Loop fell through without finding a factor
        print(n, 'is a prime number')

2 is a prime number
3 is a prime number
4 equals 2 * 2
5 is a prime number
6 equals 2 * 3
7 is a prime number
8 equals 2 * 4
9 equals 3 * 3


When used with a loop, the else clause has more in common with the else clause of a try statement than it does with that of if statements: a try statement’s else clause runs when no exception occurs, and a loop’s else clause runs when no break occurs.

The continue statement continues with the next iteration of the loop:

In [107]:
for num in range(2,10):
    if num % 2 == 0:
        print("Found an even number", num)
        continue
    print("Found a number", num)

Found an even number 2
Found a number 3
Found an even number 4
Found a number 5
Found an even number 6
Found a number 7
Found an even number 8
Found a number 9


### 4.5 pass Statements

The pass statement does nothing. It can be used when a statement is requires syntactically but the program requires no action. For example:

This is commonly used for creating minimal classes:

Another place pass can be used is as a place-holder for a function or conditional body when you are working on new code, allowing you to keep thinking at a more abstract level. The pass is silently ignored:

### 4.6 Defining Functions

We can create a function that writes the Fibonacci series to an arbitrary boundary:

In [108]:
def fib(n):           # write Fibonacci series up to n
    """Print a Fibonacci series up to n."""
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

In [109]:
# Now call the function we just defined:
fib(2000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 


The keyword def introduces a function definition. It must be followed by the function name and the parenthesized list of formal parameters. The statements that form the body of the function start at the next line, and must be indented.

The first statement of the function body can optionally be a string literal; this string literal is the function’s documentation string, or docstring. There are tools which use docstrings to automatically produce online or printed documentation, or to let the user interactively browse through code; it’s good practice to include docstrings in code that you write, so make a habit of it.

The execution of a function introduces a new symbol table used for the local variables of the function. More precisely, all variable assignments in a function store the value in the local symbol table; whereas variable references first look in the local symbol table, then in the local symbol tables of enclosing functions, then in the global symbol table, and finally in the table of built-in names. Thus, global variables and variables of enclosing functions cannot be directly assigned a value within a function (unless, for global variables, named in a global statement, or, for variables of enclosing functions, named in a nonlocal statement), although they may be referenced.

The actual parameters (arguments) to a function call are introduced in the local symbol table of the called function when it is called; thus, arguments are passed using call by value (where the value is always an object reference, not the value of the object). 1 When a function calls another function, a new local symbol table is created for that call.

A function definition introduces the function name in the current symbol table. The value of the function name has a type that is recognized by the interpreter as a user-defined function. This value can be assigned to another name which can then also be used as a function. This serves as a general renaming mechanism:

In [110]:
fib

<function __main__.fib(n)>

In [111]:
f = fib

In [112]:
f(100)

0 1 1 2 3 5 8 13 21 34 55 89 


Coming from other languages, you might object that fib is not a function but a procedure since it doesn’t return a value. In fact, even functions without a return statement do return a value, albeit a rather boring one. This value is called None (it’s a built-in name). Writing the value None is normally suppressed by the interpreter if it would be the only value written. You can see it if you really want to using print()

In [113]:
fib(0)

In [114]:
print(fib(0))


None


It is simple to write a function that returns a list of the numbers of the Fibonacci series, instead of printing it:

In [115]:
def fib2(n):     # return Fibonacci series up to n
    """Return a list containing the Fibonacci series up to n."""
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)    # see below
        a, b = b, a+b
    return result

In [116]:
f100 = fib2(100)      # call it

In [117]:
f100                  # write the result

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

The return statement returns with a value from a function. return without an expression argument returns None. Falling off the end of a function also returns None.

The statement result.append(a) calls a method of the list object result. A method is a function that ‘belongs’ to an object and is named obj.methodname, where obj is some object (this may be an expression), and methodname is the name of a method that is defined by the object’s type. Different types define different methods. Methods of different types may have the same name without causing ambiguity. (It is possible to define your own object types and methods, using classes, see Classes) The method append() shown in the example is defined for list objects; it adds a new element at the end of the list. In this example it is equivalent to result = result + [a], but more efficient.

### More on Defining Functions

It is also possible to define functions with a variable number of arguments. These are three forms, wich can be combined.

#### 4.7.1 Default Argument Values

The most useful form is to specify a default value for one or more arguments. This creates a function that can be called with fewer arguments than it is defined to allow. For example:

In [118]:
def ask_ok(prompt, retries=4, reminder='Please try again!'):
    while True:
        ok = input(prompt)
        if ok in ('y', 'ye', 'yes'):
            return True
        if ok in ('n', 'no', 'nop', 'nope'):
            return False
        retries = retries - 1
        if retrieves < 0:
            raise ValueError('invalid user response')
        print(reminder)

This function can be called in several ways:

- giving only the mandatory argument: ask_ok('Do you really want to quit?')
- giving one of the optional arguments: ask_ok('OK to overwrite the file?', 2)
- or even giving all arguments: ask_ok('OK to overwrite the file?', 2, 'Come on, only yes or no!')

This example also introduces the in keyword. This tests whether or not a sequence contains a certain value.

The default values are evaluated at the point of function definition in the defining scope, so the example below will print 5:

In [119]:
i = 5

In [120]:
def f(arg=i):
    print(arg)

In [121]:
i = 6

In [122]:
f()

5


Important warning: The default value is evaluated only once. This makes a difference when the default is a mutable object such as a list, dictionary, or instances of most classes. For example, the following function accumulates the arguments passed to it on subsequent calls.

In [123]:
def f(a, L=[]):
    L.append(a)
    return L

In [124]:
print(f(1))

[1]


In [125]:
print(f(2))

[1, 2]


In [126]:
print(f(3))

[1, 2, 3]


If you don’t want the default to be shared between subsequent calls, you can write the function like this instead:

In [127]:
def f(a, L=None):
    if L is None:
        L = []
    L.append(a)
    return L

In [128]:
print(f(1))

[1]


In [129]:
print(f(2))

[2]


In [130]:
print(f(3))

[3]


#### 4.7.2 Keyword Arguments

Functions can also be called using keyword arguments of the form kwarg=value. For instance, the following function:

In [131]:
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.")
    print("-- Lovely plumage, the", type)
    print("-- It's", state, "!")

accepts one required argument (voltage) and three optional arguments (state, action, and type). This function can be called in any of the following ways:

In [132]:
parrot(1000)                                          # 1 positional argument
parrot(voltage=1000)                                  # 1 keyword argument
parrot(voltage=1000000, action='VOOOOOM')             # 2 keyword arguments
parrot(action='VOOOOOM', voltage=1000000)             # 2 keyword arguments
parrot('a million', 'bereft of life', 'jump')         # 3 positional arguments
parrot('a thousand', state='pushing up the daisies')  # 1 positional, 1 keyword

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't jump if you put a million volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's bereft of life !
-- This parrot wouldn't voom if you put a thousand volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's pushing up the daisies !


but all the following calls would be invalid:

In [133]:
parrot()                     # required argument missing
parrot(voltage=5.0, 'dead')  # non-keyword argument after a keyword argument
parrot(110, voltage=220)     # duplicate value for the same argument
parrot(actor='John Cleese')  # unknown keyword argument

SyntaxError: positional argument follows keyword argument (<ipython-input-133-2ac707ad11c1>, line 2)

In a function call, keyword arguments must follow positional arguments. All the keyword arguments passed must match one of the arguments accepted by the function (e.g. actor is not a valid argument for the parrot function), and their order is not important. This also includes non-optional arguments (e.g. parrot(voltage=1000) is valid too). No argument may receive a value more than once. Here’s an example that fails due to this restriction:

In [134]:
def function (a):
    pass

In [135]:
function (0, a=0)

TypeError: function() got multiple values for argument 'a'

When a final formal parameter of the form \*\*name is present, it receives a dictionary containing all keyword arguments except for those corresponding to a formal parameter. This may be combined with a formal parameter of the form \*name which receives a tuple containing the positional arguments beyond the formal parameter list. (\*name must occur before \*\*name.) For example, if we define a function like this:

In [136]:
def cheeseshop(kind, *arguments, **keywords):
    print("-- Do you have any", kind, "?")
    print("-- I'm sorry, we're all out of", kind)
    for arg in arguments:
        print(arg)
    print("-" * 40)
    for kw in keywords:
        print(kw, ":", keywords[kw])

In [137]:
cheeseshop("Limburger", "It's very runny, sir.",
           "It's really very, VERY runny, sir.",
           shopkeeper="Michael Palin",
           client="John Cleese",
           sketch="Cheese Shop Sketch")

-- Do you have any Limburger ?
-- I'm sorry, we're all out of Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
----------------------------------------
shopkeeper : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch


Note that the order in which the keyword arguments are printed is guaranteed to match the order in which they were provided in the function call.

#### 4.7.3 Special parameters

By default, arguments may be passed to a Python function either by position or explicitly by keyword. For readability and performance, it makes sense to restrict the way arguments can be passed so that a developer need only look at the function definition to determine if items are passed by position, by position or keyword, or by keyword.

A function definition may look like:

where / and * are optional. If used, these symbols indicate the kind of parameter by how the arguments may be passed to the function: positional-only, positional-or-keyword, and keyword-only. Keyword parameters are also referred to as named parameters.

- Positional-or-Keyword Arguments

If / and * are not present in the function definition, arguments may be passed to a function by position or by keyword.
- Positional-Only Parameters

Looking at this in a bit more detail, it is possible to mark certain parameters as positional-only. If positional-only, the parameters’ order matters, and the parameters cannot be passed by keyword. Positional-only parameters are placed before a / (forward-slash). The / is used to logically separate the positional-only parameters from the rest of the parameters. If there is no / in the function definition, there are no positional-only parameters. Parameters following the / may be positional-or-keyword or keyword-only.
- Keyword-Only Arguments

To mark parameters as keyword-only, indicating the parameters must be passed by keyword argument, place an * in the arguments list just before the first keyword-only parameter.

Consider the following example function definitions paying close attention to the markers / and *:

*Note: due to Python version supported by Anaconda doesn't support / marker, the code sections that use it wouldn't be executed, so its repective response was added manually.

In [138]:
def standard_arg(arg):
    print(arg)

In [139]:
def kwd_only_arg(*, arg):
    print(arg)

The first function definition, standard_arg, the most familiar form, places no restrictions on the calling convention and arguments may be passed by position or keyword:

In [140]:
standard_arg(2)

2


In [141]:
standard_arg(arg=2)

2


The second function pos_only_arg is restricted to only use positional parameters as there is a / in the function definition:

1

The third function kwd_only_args only allows keyword arguments as indicated by a * in the function definition:

In [142]:
kwd_only_arg(3)

TypeError: kwd_only_arg() takes 0 positional arguments but 1 was given

In [143]:
kwd_only_arg(arg=3)

3


And the last uses all three calling conventions in the same function definition:

1   2   3

1 2 3

Finally, consider this function definition which has a potential collision between the positional argument name and \*\*kwds which has name as a key:

In [144]:
def foo(name, **kwds):
    return 'name' in kwds

There is no possible call that will make it return True as the keyword 'name' will always to bind to the first parameter. For example:

In [145]:
foo(1, **{'name': 2})

TypeError: foo() got multiple values for argument 'name'

But using / (positional only arguments), it is possible since it allows name as a positional argument and 'name' as a key in the keyword arguments:

True

In other words, the names of positional-only parameters can be used in \*\*kwds without ambiguity.

- Recap

The use case will determine which parameters to use in the function definition:

As guidance:

- Use positional-only if you want the name of the parameters to not be available to the user. This is useful when parameter names have no real meaning, if you want to enforce the order of the arguments when the function is called or if you need to take some positional parameters and arbitrary keywords.

- Use keyword-only when names have meaning and the function definition is more understandable by being explicit with names or you want to prevent users relying on the position of the argument being passed.

- For an API, use positional-only to prevent breaking API changes if the parameter’s name is modified in the future.

#### 4.7.4 Arbitrary Argument Lists

Finally, the least frequently used option is to specify that a function can be called with an arbitrary number of arguments. These arguments will be wrapped up in a tuple. Before the variable number of arguments, zero or more normal arguments may occur.

In [146]:
def write_multiple_items(file, separator, *args):
    file.write(separator.join(args))

Normally, these variadic arguments will be last in the list of formal parameters, because they scoop up all remaining input arguments that are passed to the function. Any formal parameters which occur after the *args parameter are ‘keyword-only’ arguments, meaning that they can only be used as keywords rather than positional arguments.

In [147]:
def concat(*args, sep="/"):
    return sep.join(args)

In [148]:
concat("earth", "mars", "venus")

'earth/mars/venus'

In [149]:
concat("earth", "mars", "venus", sep=".")

'earth.mars.venus'

#### 4.7.5 Unpacking Argument Lists

The reverse situation occurs when the arguments are already in a list or tuple but need to be unpacked for a function call requiring separate positional arguments. For instance, the built-in range() function expects separate start and stop arguments. If they are not available separately, write the function call with the \*-operator to unpack the arguments out of a list or tuple:

In [150]:
list(range(3, 6))            # normal call with separate arguments

[3, 4, 5]

In [151]:
args = [3, 6]

In [152]:
list(range(*args))            # call with arguments unpacked from a list

[3, 4, 5]

In the same fashion, dictionaries can deliver keyword arguments with the \*\*-operator:

In [153]:
def parrot(voltage, state='a stiff', action='voom'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.", end=' ')
    print("E's", state, "!")

In [154]:
d = {"voltage": "four million", "state": "bleedin' demised", "action": "VOOM"}

In [155]:
parrot(**d)

-- This parrot wouldn't VOOM if you put four million volts through it. E's bleedin' demised !


#### 4.7.6 Lambda Expressions

Small anonymous functions can be created with the lambda keyword. This function returns the sum of its two arguments: lambda a, b: a+b. Lambda functions can be used wherever function objects are required. They are syntactically restricted to a single expression. Semantically, they are just syntactic sugar for a normal function definition. Like nested function definitions, lambda functions can reference variables from the containing scope:

In [156]:
def make_incrementor(n):
    return lambda x: x + n

In [157]:
f = make_incrementor(42)

In [158]:
f(0)

42

In [159]:
f(1)

43

The above example uses a lambda expression to return a function. Another use is to pass a small function as an argument:

In [160]:
pairs = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]

In [161]:
pairs.sort(key=lambda pair: pair[1])

In [162]:
pairs

[(4, 'four'), (1, 'one'), (3, 'three'), (2, 'two')]

#### Documentation Strings

Here are some conventions about the content and formatting of documentation strings.

The first line should always be a short, concise summary of the object’s purpose. For brevity, it should not explicitly state the object’s name or type, since these are available by other means (except if the name happens to be a verb describing a function’s operation). This line should begin with a capital letter and end with a period.

If there are more lines in the documentation string, the second line should be blank, visually separating the summary from the rest of the description. The following lines should be one or more paragraphs describing the object’s calling conventions, its side effects, etc.

The Python parser does not strip indentation from multi-line string literals in Python, so tools that process documentation have to strip indentation if desired. This is done using the following convention. The first non-blank line after the first line of the string determines the amount of indentation for the entire documentation string. (We can’t use the first line since it is generally adjacent to the string’s opening quotes so its indentation is not apparent in the string literal.) Whitespace “equivalent” to this indentation is then stripped from the start of all lines of the string. Lines that are indented less should not occur, but if they occur all their leading whitespace should be stripped. Equivalence of whitespace should be tested after expansion of tabs (to 8 spaces, normally).

Here is an example of multi-line docstring:

In [163]:
def my_function():
    """Do nothing, but document it.
    
    No, really, it doesn't do anything.
    """
    pass

In [164]:
print(my_function.__doc__)

Do nothing, but document it.
    
    No, really, it doesn't do anything.
    


#### 4.7.8 Function Annotations

Function annotations are completely optional metadata information about the types used by user-defined functions.

Annotations are stored in the \_\_annotations\_\_ attribute of the function as a dictionary and have no effect on any other part of the function. Parameter annotations are defined by a colon after the parameter name, followed by an expression evaluating to the value of the annotation. Return annotations are defined by a literal ->, followed by an expression, between the parameter list and the colon denoting the end of the def statement. The following example has a positional argument, a keyword argument, and the return value annotated:

In [165]:
def f(ham: str, eggs: str = 'eggs') -> str:
    print("Annotations:", f.__annotations__)
    print("Arguments:", ham, eggs)
    return ham + ' and ' + eggs

In [166]:
f('spam')

Annotations: {'ham': <class 'str'>, 'eggs': <class 'str'>, 'return': <class 'str'>}
Arguments: spam eggs


'spam and eggs'

### 4.8 Intermezzo: Coding Style

Now that you are about to write longer, more complex pieces of Python, it is a good time to talk about coding style. Most languages can be written (or more concise, formatted) in different styles; some are more readable than others. Making it easy for others to read your code is always a good idea, and adopting a nice coding style helps tremendously for that.

For Python, PEP 8 has emerged as the style guide that most projects adhere to; it promotes a very readable and eye-pleasing coding style. Every Python developer should read it at some point; here are the most important points extracted for you:

- Use 4-space indentation, and no tabs. 4 spaces are a good compromise between small indentation (allows greater nesting depth) and large indentation (easier to read). Tabs introduce confusion, and are best left out.

- Wrap lines so that they don’t exceed 79 characters. This helps users with small displays and makes it possible to have several code files side-by-side on larger displays.

- Use blank lines to separate functions and classes, and larger blocks of code inside functions.

- When possible, put comments on a line of their own.

- Use docstrings.

- Use spaces around operators and after commas, but not directly inside bracketing constructs: a = f(1, 2) + g(3, 4).

- Name your classes and functions consistently; the convention is to use UpperCamelCase for classes and lowercase_with_underscores for functions and methods. Always use self as the name for the first method argument (see A First Look at Classes for more on classes and methods).

- Don’t use fancy encodings if your code is meant to be used in international environments. Python’s default, UTF-8, or even plain ASCII work best in any case.

- Likewise, don’t use non-ASCII characters in identifiers if there is only the slightest chance people speaking a different language will read or maintain the code.

## 5. Data Structures

### 5.1 More on Lists

The list data type has some more methods. Here are all of the methods of list objects:

list.**append**(x)
Add an item to the end of the list. Equivalent to a[len(a):] = [x].

list.**extend**(iterable)
Extend the list by appending all the items from the iterable. Equivalent to a[len(a):] = iterable.

list.**insert**(i, x)
Insert an item at a given position. The first argument is the index of the element before which to insert, so a.insert(0, x) inserts at the front of the list, and a.insert(len(a), x) is equivalent to a.append(x).

list.**remove**(x)
Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

list.**pop**([i])
Remove the item at the given position in the list, and return it. If no index is specified, a.pop() removes and returns the last item in the list. (The square brackets around the i in the method signature denote that the parameter is optional, not that you should type square brackets at that position. You will see this notation frequently in the Python Library Reference.)

list.**clear**()
Remove all items from the list. Equivalent to del a[:].

list.**index**(x[, start[, end]])
Return zero-based index in the list of the first item whose value is equal to x. Raises a ValueError if there is no such item.

The optional arguments start and end are interpreted as in the slice notation and are used to limit the search to a particular subsequence of the list. The returned index is computed relative to the beginning of the full sequence rather than the start argument.

list.**count**(x)
Return the number of times x appears in the list.

list.**sort**(key=None, reverse=False)
Sort the items of the list in place (the arguments can be used for sort customization, see sorted() for their explanation).

list.**reverse**()
Reverse the elements of the list in place.

list.**copy**()
Return a shallow copy of the list. Equivalent to a[:].

An example that uses most of the list methods:

In [167]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

In [168]:
fruits.count('apple')

2

In [169]:
fruits.count('tangerine')

0

In [170]:
fruits.index('banana')

3

In [171]:
fruits.index('banana', 4)  # Find next banana starting a position 4

6

In [172]:
fruits.reverse()

In [173]:
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [174]:
fruits.append('grape')

In [175]:
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']

In [176]:
fruits.sort()

In [177]:
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']

In [178]:
fruits.pop()

'pear'

You might have noticed that methods like insert, remove or sort that only modify the list have no return value printed – they return the default None. 1 This is a design principle for all mutable data structures in Python.

Another thing you might notice is that not all data can be sorted or compared. For instance, [None, 'hello', 10] doesn’t sort because integers can’t be compared to strings and None can’t be compared to other types. Also, there are some types that don’t have a defined ordering relation. For example, 3+4j < 5+7j isn’t a valid comparison.

#### 5.1.1. Using Lists as Stacks

The list methods make it very easy to use a list as a stack, where the last element added is the first element retrieved (“last-in, first-out”). To add an item to the top of the stack, use append(). To retrieve an item from the top of the stack, use pop() without an explicit index. For example:

In [179]:
stack = [3, 4, 5]

In [180]:
stack.append(6)

In [181]:
stack.append(7)

In [182]:
stack

[3, 4, 5, 6, 7]

In [183]:
stack.pop()

7

In [184]:
stack

[3, 4, 5, 6]

In [185]:
stack.pop()

6

In [186]:
stack.pop()

5

In [187]:
stack

[3, 4]

#### 5.1.2 Using Lists as Queues

It is also possible to use a list as a queue, where the first element added is the first element retrieved (“first-in, first-out”); however, lists are not efficient for this purpose. While appends and pops from the end of list are fast, doing inserts or pops from the beginning of a list is slow (because all of the other elements have to be shifted by one).

To implement a queue, use collections.deque which was designed to have fast appends and pops from both ends. For example:

In [188]:
from collections import deque

In [189]:
queue = deque(["Eric", "John", "Michael"])

In [190]:
queue.append("Terry")           # Terry arrives

In [191]:
queue.append("Graham")          # Graham arrives

In [192]:
queue.popleft()                 # The first to arrive now leaves

'Eric'

In [193]:
queue.popleft()                 # The second to arrive now leaves

'John'

In [194]:
queue                           # Remaining queue in order of arrival

deque(['Michael', 'Terry', 'Graham'])

#### 5.1.3 List Comprehensions

List comprehensions provide a concise way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

For example, assume we want to create a list of squares, like:

In [195]:
squares = []

In [196]:
for x in range(10):
    squares.append(x**2)

In [197]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Note that this creates (or overwrites) a variable named x that still exists after the loop completes. We can calculate the list of squares without any side effects using:

In [198]:
squares = list(map(lambda x: x**2, range(10)))

or equivalently:

In [199]:
squares = [x**2 for x in range(10)]

which is more concise and readable.

A list comprehension consists of brackets containing an expression followed by a for clause, then zero or more for or if clauses. The result will be a new list resulting from evaluating the expression in the context of the for and if clauses which follow it. For example, this listcomp combines the elements of two lists if they are not equal:

In [200]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

and it's equivalent to:

In [201]:
combs = []

In [202]:
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x,y))

In [203]:
combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

Note how the order of the for and if statements is the same in both these snippets.

If the expression is a tuple (e.g. the (x, y) in the previous example), it must be parenthesized.

In [204]:
vec = [-4, -2, 0, 2, 4]

In [205]:
# create a new list with the values doubled
[x*2 for x in vec]

[-8, -4, 0, 4, 8]

In [206]:
# filfer the list to exclude negative numbers
[x for x in vec if x >= 0]

[0, 2, 4]

In [207]:
# apply a function to all the elements
[abs(x) for x in vec]

[4, 2, 0, 2, 4]

In [208]:
# call a method on each element
freshfruit = [' banana ', ' loganberry ', ' passion fruit ']
[weapon.strip() for weapon in freshfruit]

['banana', 'loganberry', 'passion fruit']

In [209]:
# create a list of 2-tuples like (number, square)
[(x, x**2) for x in range(6)]

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

In [210]:
# the tuple must be parenthesized, otherwise an error is raised
[x, x**2 for x in range(6)]

SyntaxError: invalid syntax (<ipython-input-210-702d12ece8a4>, line 2)

In [211]:
# flatten a list using a listcomp with two 'for'
vec = [[1,2,3], [4,5,6], [7,8,9]]

In [212]:
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

List comprehensions can contain complex expressions and nested functions:

In [213]:
from math import pi

In [214]:
[str(round(pi, i)) for i in range(1, 6)]

['3.1', '3.14', '3.142', '3.1416', '3.14159']

#### 5.1.4 Nested List Comprehensions

The initial expression in a list comprehension can be any arbitrary expression, including another list comprehension.

Consider the following example of a 3x4 matrix implemented as a list of 3 lists of length 4:

In [215]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

The following list comprehension will transpose rows and columns:

In [216]:
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

As we saw in the previous section, the nested listcomp is evaluated in the context of the for that follows it, so this example is equivalent to:

In [217]:
transposed = []

In [218]:
for i in range(4):
    transposed.append([row[i] for row in matrix])

In [219]:
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

which, in turn, is the same as:

In [220]:
transposed = []

In [221]:
for i in range(4):
    # the following 3 lines implement the nested listcomp
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)

In [222]:
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

You should prefer built-in functions to complex flow statements. The zip() function would do a great job for this use case:

In [223]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

### 5.2 The del statement

There is a way to remove an item from a list given its index instead of its value: the del statement. This differs from the pop() method which returns a value. The del statement can also be used to remove slices from a list or clear the entire list. For example:

In [224]:
a = [-1, 1, 66.25, 333, 333, 1234.5]

In [225]:
del a[0]

In [226]:
a

[1, 66.25, 333, 333, 1234.5]

In [227]:
del a[2:4]

In [228]:
a

[1, 66.25, 1234.5]

In [229]:
del a[:]

In [230]:
a

[]

del can also be used to delete entire variables:

In [231]:
del a

### 5.3 Tuples and Sequences

A tuple consists of a number of values separated by commas, for instance:

In [232]:
t = 12345, 54321, 'hello!'

In [233]:
t[0]

12345

In [234]:
t

(12345, 54321, 'hello!')

In [235]:
# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)

In [236]:
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

In [237]:
# Tuples are immutable:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

In [238]:
# but they can contain mutable objcts:
v = ([1, 2, 3], [3, 2, 1])

In [239]:
v

([1, 2, 3], [3, 2, 1])

As you see, on output tuples are always enclosed in parentheses, so that nested tuples are interpreted correctly; they may be input with or without surrounding parentheses, although often parentheses are necessary anyway (if the tuple is part of a larger expression). It is not possible to assign to the individual items of a tuple, however it is possible to create tuples which contain mutable objects, such as lists.

Though tuples may seem similar to lists, they are often used in different situations and for different purposes. Tuples are immutable, and usually contain a heterogeneous sequence of elements that are accessed via unpacking or indexing (or even by attribute in the case of namedtuples). Lists are mutable, and their elements are usually homogeneous and are accessed by iterating over the list.

A special problem is the construction of tuples containing 0 or 1 items: the syntax has some extra quirks to accommodate these. Empty tuples are constructed by an empty pair of parentheses; a tuple with one item is constructed by following a value with a comma (it is not sufficient to enclose a single value in parentheses). Ugly, but effective. For example:

In [240]:
empty = ()

In [241]:
singleton = 'hello',    # <-- note trailing comma

In [242]:
len(empty)

0

In [243]:
len(singleton)

1

In [244]:
singleton

('hello',)

The statement t = 12345, 54321, 'hello!' is an example of tuple packing: the values 12345, 54321 and 'hello!' are packed together in a tuple. The reverse operation is also possible:

In [245]:
x, y, z = t

This is called, appropriately enough, sequence unpacking and works for any sequence on the right-hand side. Sequence unpacking requires that there are as many variables on the left side of the equals sign as there are elements in the sequence. Note that multiple assignment is really just a combination of tuple packing and sequence unpacking.

### 5.4. Sets

Python also includes a data type for sets. A set is an unordered collection with no duplicate elements. Basic uses include membership testing and eliminating duplicate entries. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

Curly braces or the set() function can be used to create sets. 

*Note: to create an empty set you have to use set(), not {}; the latter creates an empty dictionary, a data structure that we discuss in the next section.

Here is a brief demonstration:

In [246]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}

In [247]:
print(basket)                 # show that duplicates have been removed

{'pear', 'apple', 'banana', 'orange'}


In [248]:
'orange' in basket            # fast membership testing

True

In [249]:
'crabgrass' in basket

False

In [250]:
# Demostrate set operations on unique letters from two words

In [251]:
a = set('abracadabra')

In [252]:
b = set('alacazam')

In [253]:
a                           # unique letters in a

{'a', 'b', 'c', 'd', 'r'}

In [254]:
a - b                       # letters in a but not in b

{'b', 'd', 'r'}

In [255]:
a | b                       # letters in a or b or both

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [256]:
a & b                       # letters in both a and b

{'a', 'c'}

In [257]:
a ^ b                       # letters in a or b but not both

{'b', 'd', 'l', 'm', 'r', 'z'}

Similarly to list comprehensions, set comprehensions are also supported:

In [258]:
a = {x for x in 'abracadabra' if x not in 'abc'}

In [259]:
a

{'d', 'r'}

### 5.5 Dictionaries

Dictionaries are sometimes found in other languages as “associative memories” or “associative arrays”. Unlike sequences, which are indexed by a range of numbers, dictionaries are indexed by keys, which can be any immutable type; strings and numbers can always be keys. Tuples can be used as keys if they contain only strings, numbers, or tuples; if a tuple contains any mutable object either directly or indirectly, it cannot be used as a key. You can’t use lists as keys, since lists can be modified in place using index assignments, slice assignments, or methods like append() and extend().

It is best to think of a dictionary as a set of key: value pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: {}. Placing a comma-separated list of key:value pairs within the braces adds initial key:value pairs to the dictionary; this is also the way dictionaries are written on output.

The main operations on a dictionary are storing a value with some key and extracting the value given the key. It is also possible to delete a key:value pair with del. If you store using a key that is already in use, the old value associated with that key is forgotten. It is an error to extract a value using a non-existent key.

Performing list(d) on a dictionary returns a list of all the keys used in the dictionary, in insertion order (if you want it sorted, just use sorted(d) instead). To check whether a single key is in the dictionary, use the in keyword.

Here is a small example using a dictionary:

In [260]:
tel = {'jack': 4098, 'sape': 4139}

In [261]:
tel['guido'] = 4127

In [262]:
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [263]:
tel['jack']

4098

In [264]:
del tel['sape']

In [265]:
tel['irv'] = 4127

In [266]:
tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [267]:
list(tel)

['jack', 'guido', 'irv']

In [268]:
sorted(tel)

['guido', 'irv', 'jack']

In [269]:
'guido' in tel

True

In [270]:
'jack' not in tel

False

The dict() constructor builds dictionaries directly from sequences of key-value pairs:

In [271]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In addition, dict comprehensions can be used to create dictionaries from arbitrary key and value expressions:

In [272]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

When the keys are simple strings, it is sometimes easier to specify pairs using keyword arguments:

In [273]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

### 5.6 Looping Techniques

When looping through dictionaries, the key and corresponding value can be retrieved at the same time using the items() method.

In [274]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}

In [275]:
for k, v in knights.items():
    print(k, v)

gallahad the pure
robin the brave


When looping through a sequence, the position index and corresponding value can be retrieved at the same time using the enumerate() function.

In [276]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


To loop over two or more sequences at the same time, the entries can be paired with the zip() function.

In [277]:
questions = ['name', 'quest', 'favorite color']

In [278]:
answers = ['lancelot', 'the holy grail', 'blue']

In [279]:
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


To loop over a sequence in reverse, first specify the sequence in a forward direction and then call the reversed() function.

In [280]:
for i in reversed(range(1, 10, 2)):
    print(i)

9
7
5
3
1


To loop over a sequence in sorted order, use the sorted() function which returns a new sorted list while leaving the source unaltered.

In [281]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']

In [282]:
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


It is sometimes tempting to change a list while you are looping over it; however, it is often simpler and safer to create a new list instead.

In [283]:
import math

In [284]:
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]

In [285]:
filtered_data = []

In [286]:
for value in raw_data:
    if not math.isnan(value):
        filtered_data.append(value)

In [287]:
filtered_data

[56.2, 51.7, 55.3, 52.5, 47.8]

### 5.7. More on Conditions

The conditions used in while and if statements can contain any operators, not just comparisons.

The comparison operators in and not in check whether a value occurs (does not occur) in a sequence. The operators is and is not compare whether two objects are really the same object; this only matters for mutable objects like lists. All comparison operators have the same priority, which is lower than that of all numerical operators.

Comparisons can be chained. For example, a < b == c tests whether a is less than b and moreover b equals c.

Comparisons may be combined using the Boolean operators and and or, and the outcome of a comparison (or of any other Boolean expression) may be negated with not. These have lower priorities than comparison operators; between them, not has the highest priority and or the lowest, so that A and not B or C is equivalent to (A and (not B)) or C. As always, parentheses can be used to express the desired composition.

The Boolean operators and and or are so-called short-circuit operators: their arguments are evaluated from left to right, and evaluation stops as soon as the outcome is determined. For example, if A and C are true but B is false, A and B and C does not evaluate the expression C. When used as a general value and not as a Boolean, the return value of a short-circuit operator is the last evaluated argument.

It is possible to assign the result of a comparison or other Boolean expression to a variable. For example,

In [288]:
string1, string2, string3 = '', 'Trondheim', 'Hammer Dance'

In [289]:
non_null = string1 or string2 or string3

In [290]:
non_null

'Trondheim'

### 5.8. Comparing Sequences and Other Types

Sequence objects typically may be compared to other objects with the same sequence type. The comparison uses lexicographical ordering: first the first two items are compared, and if they differ this determines the outcome of the comparison; if they are equal, the next two items are compared, and so on, until either sequence is exhausted. If two items to be compared are themselves sequences of the same type, the lexicographical comparison is carried out recursively. If all items of two sequences compare equal, the sequences are considered equal. If one sequence is an initial sub-sequence of the other, the shorter sequence is the smaller (lesser) one. Lexicographical ordering for strings uses the Unicode code point number to order individual characters. Some examples of comparisons between sequences of the same type:

Note that comparing objects of different types with < or > is legal provided that the objects have appropriate comparison methods. For example, mixed numeric types are compared according to their numeric value, so 0 equals 0.0, etc. Otherwise, rather than providing an arbitrary ordering, the interpreter will raise a TypeError exception.